services:
  - type: web
    name: yukpomnang-backend
    env: rust
    rootDir: backend
    buildCommand: cargo build --release
    startCommand: cargo run --release
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RUST_LOG
        value: info
    healthCheckPath: /health
    plan: starter
