MITservices:
  - type: web
    name: yukpomnang-backend
    env: rust
    buildCommand: |
      cd backend
      cargo build --release
    startCommand: ./render-migrate.sh
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RUST_LOG
        value: info
      - key: RUST_BACKTRACE
        value: 1
    healthCheckPath: /health
    plan: starter
